// citations.js
let citations = [
  { texte: "La patience est la clé du succès." },
  { texte: "Qui cherche la vérité la trouvera." },
  { texte: "Every being deserves mercy." },
  { texte: "La gratitude transforme ce que nous avons en suffisance." },
  { texte: "Ne remets pas à demain ce que tu peux faire aujourd'hui." },
  { texte: "Le savoir est la lumière de l'esprit." },
  { texte: "Un sourire est une courbe qui redresse tout." },
  { texte: "Celui qui ne pardonne pas se prive de la paix." },
  { texte: "Le courage ne rugit pas toujours, parfois c’est un murmure." },
  { texte: "Cherche le bien, même dans les petites choses." },
  { texte: "La foi est le pont entre le visible et l’invisible." },
  { texte: "Celui qui aime la paix trouve le bonheur." },
  { texte: "L’humilité précède l’élévation." },
  { texte: "Chaque jour est une nouvelle chance de s’améliorer." },
  { texte: "La sagesse commence par l’émerveillement." },
  { texte: "Le silence est parfois plus puissant que les mots." },
  { texte: "La générosité enrichit celui qui donne." },
  { texte: "Apprends à écouter avant de parler." },
  { texte: "La vérité se révèle à ceux qui la cherchent." },
  { texte: "Ne sous-estime jamais le pouvoir d’une prière." },
  { texte: "Le respect attire le respect." },
  { texte: "Chaque échec est une leçon déguisée." },
  { texte: "La confiance en Allah ne déçoit jamais." },
  { texte: "Le bonheur se cache dans les choses simples." },
  { texte: "Aide les autres sans rien attendre en retour." },
  { texte: "L’action précède l’inspiration." },
  { texte: "Celui qui persévère atteint le sommet." },
  { texte: "La peur diminue avec la connaissance." },
  { texte: "Le sourire est un acte de courage." },
  { texte: "Le pardon libère l’âme." },
  { texte: "La patience embellit le caractère." },
  { texte: "La foi est le moteur des actions justes." },
  { texte: "Agis avec justice et droiture." },
  { texte: "Celui qui donne avec sincérité est béni." },
  { texte: "La gratitude apaise le cœur." },
  { texte: "Cherche la lumière même dans l’obscurité." },
  { texte: "Les paroles sages sont un trésor." },
  { texte: "Le temps révèle les véritables intentions." },
  { texte: "Celui qui prie trouve la sérénité." },
  { texte: "Le respect des autres commence par soi-même." },
  { texte: "Chaque jour est un nouveau départ." },
  { texte: "L’humilité attire les bénédictions." },
  { texte: "Les actes de bonté ne se perdent jamais." },
  { texte: "Écoute ton cœur, mais guide-le avec raison." },
  { texte: "Le savoir est une lumière que personne ne peut éteindre." },
  { texte: "Celui qui aime la vérité sera aimé." },
  { texte: "Cherche la paix, et tu trouveras Allah." },
  { texte: "La prière est le refuge de l’âme." },
  { texte: "Le bien attire le bien." },
  { texte: "Sois patient face aux épreuves." },
  { texte: "La sincérité ouvre toutes les portes." }
];
